# Generated by Django 4.2 on 2025-01-30 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_created=True, auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('post', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/images/')),
            ],
        ),
    ]
